apiVersion: v1
kind: Pod
metadata:
  name: appserver
  namespace: twitter
  labels:
    app: sankar
    tier: front
    version: v1
    env: production
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
